pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template,g
from werkzeug.utils import redirect
from ..form import AnswerForm
from pybo.views.sign_views import login_required
import mariadb


bp = Blueprint('answer', __name__,url_prefix='/answer')

# 데이터베이스 연결
def connect_data():
    conn = mariadb.connect(
        user="root",
        password="1234",
        host="localhost",
        port=3306,
        database="dd_test"
    )
    return conn


#답변 생성
@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    #전달받은 폼의 제대로 입력되있는지 판단
    if form.validate_on_submit():
        conn = connect_data()
        cur = conn.cursor()
        content = request.form['content']
        print(question_id,content,g.user,datetime.now())
        cur.execute("SELECT r_id FROM reporter WHERE nick_name = '{}' ".format(g.user))
        reporter = cur.fetchone()
        cur.execute("""INSERT INTO answer
(p_id, content, reporter, reg_date, pub_date)
VALUES({}, '{}', {}, current_timestamp(), NULL);""".format(question_id,content,reporter[0]))
        conn.commit()

        return redirect(url_for('question.detail', q=question_id))
    return render_template('question/question_detail.html', question=question_id, form=form)

pybo/views/question_views.py
# ---------------------------------------- [edit] ---------------------------------------- #
from flask import Blueprint, render_template  , url_for, request,g , session
from werkzeug.utils import redirect, secure_filename
import os
from ..form import QuestionForm, AnswerForm ,SearchForm
from pybo.views.sign_views import login_required
import mariadb
import sys
import math
from flask import Flask, send_from_directory, send_file
import datetime


# 파일 업로드와 다운로드파일을 관리하는 폴더의 경로
path = '/home/ubuntu/projects/myproject/pybo/uploads'

bp = Blueprint('question', __name__, url_prefix='/question')

# 데이터베이스 연결
def connect_data():
    conn = mariadb.connect(
        user="root",
        password="1234",
        host="localhost",
        port=3306,
        database="dd_test"
    )
    return conn

# 질문 목록
@bp.route('/list/', methods=('GET','POST'))
def _list():
    form = SearchForm()

    p_page = request.args.get('page',type=int,default=1)
    per_page = 10
    limit = (p_page - 1) * 10
    #POST 방식으로 호출되었다면 입력받은 단어를 검색
    if request.method == 'POST' and form.validate_on_submit():
        word = form.searchword.data
        conn = connect_data()
        cur = conn.cursor()
        cur.execute("""SELECT count(*) 
        FROM post  
        WHERE content LIKE '%{}%';""".format(word))
        total_cnt = len(cur.fetchall())
        total_page = math.floor(total_cnt/per_page) + 2
        cur.execute("""SELECT p.p_id, p.title , p.content, r.nick_name, p.reg_date 
                FROM post as p 
                LEFT JOIN reporter as r 
                ON p.reporter = r.r_id
                WHERE p.title LIKE '%{}%' ORDER BY p_id DESC limit {},10;""".format(word, limit))
        question_list = cur.fetchall()
        return render_template('question/question_list.html', question_list=question_list, lp = total_page, p_page=p_page, form = form)

    conn = connect_data()
    cur = conn.cursor()
    cur.execute("SELECT count(*) FROM post")
    total_cnt = cur.fetchone()
    total_page = math.floor(total_cnt[0]/per_page) + 2
    cur.execute("SELECT p.p_id,p.title,p.content,r.nick_name,p.reg_date FROM post as p LEFT JOIN reporter as r ON p.reporter = r.r_id ORDER BY p_id DESC limit {},10".format(limit))
    question_list = cur.fetchall()


    return render_template('question/question_list.html', question_list=question_list, lp = total_page,p_page=p_page, form=form)

# 질문 상세 페이지
@bp.route('/detail/')
def detail():
    q = request.args.get('q',type=int)
    form = AnswerForm()
    conn = connect_data()
    cur = conn.cursor()
    cur.execute("SELECT title , content , reporter , reg_date , p_id, imgfile FROM post where p_id = {} ".format(q))
    question = cur.fetchone()
    cur.execute("SELECT nick_name FROM reporter WHERE r_id = {}".format(question[2]))
    reporter = cur.fetchone()
    cur.execute("SELECT a.content, a.reg_date, r.nick_name FROM answer a LEFT JOIN reporter as r ON r.r_id = a.reporter WHERE p_id = {}".format(q))
    answer = cur.fetchall()


    return render_template('question/question_detail.html', question=question, form=form, reporter = reporter , answer = answer)

# 업로드하려는 파일이 서버에 업로드되어있는지 체크하는 재귀함수
def checkfile(file):
    conn = connect_data()
    cur = conn.cursor()
    f = file
    cur.execute("SELECT imgfile FROM post WHERE imgfile = '{}'".format(f))
    checkimg = cur.fetchone()
    if checkimg:
        f = '(1)' + f
        return checkfile(f)
    else:
        return f

# 질문 생성(세션에 로그인 되어있어야함)
@bp.route('/create/', methods=('GET','POST'))
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        conn = connect_data()
        cur = conn.cursor()
        path = 'c:/projects/myproject/pybo/uploads/'

        if request.files['file']:

            f = request.files['file']
            name = checkfile(f.filename)

            f.save(path+ name)
            cur = conn.cursor()
            cur.execute("SELECT r_id FROM reporter WHERE nick_name = '{}'".format(g.user))
            reporter = cur.fetchone()
            cur.execute("""INSERT INTO post
                        (title, content, reporter, reg_date, pub_date,imgfile)
                        VALUES('{}','{}', {}, current_timestamp(), NULL,'{}');""".format(form.subject.data,
                                                                                         form.content.data,
                                                                                         reporter[0], name))
            conn.commit()
        else:


            cur = conn.cursor()
            cur.execute("SELECT r_id FROM reporter WHERE nick_name = '{}'".format(g.user))
            reporter = cur.fetchone()
            cur.execute("""INSERT INTO post
            (title, content, reporter, reg_date, pub_date,imgfile)
            VALUES('{}','{}', {}, current_timestamp(), NULL, NULL);""".format(form.subject.data, form.content.data,
                                                                             reporter[0]))
            conn.commit()






        return redirect(url_for('question._list'))
    return render_template('question/question_form.html', form=form)





# 게시글 삭제
@bp.route('/delete')
def post_delete():
    user_id = session.get('user_id')
    question_name = request.args.get('user', type=str)
    if user_id == "admin":
        p_id = request.args.get('p_id', type=int)
        conn = connect_data()
        cur = conn.cursor()
        cur.execute("DELETE FROM post WHERE p_id = {}".format(p_id))
        conn.commit()
        return redirect(url_for('question._list'))

    elif user_id == question_name:
        p_id = request.args.get('p_id', type=int)
        conn = connect_data()
        cur = conn.cursor()
        cur.execute("DELETE FROM post WHERE p_id = {}".format(p_id))
        conn.commit()

        return redirect(url_for('question._list'))
    return redirect(url_for('question._list'))

# 파일 다운로드
@bp.route('download')
@login_required
def download():
    imgnum = request.args.get('img', type=str)

    return send_file(path + imgnum, attachment_filename= imgnum,as_attachment=True)

pybo/templates/question/question_detail.html
{% extends 'pro.html' %}
{% block content %}
<div class="container my-3 table-responsive table-secondary shadow rounded-sm">
    <h2 class="border-bottom py-2">{{ question[0] }}</h2>
    <div class="card my-3">
        {% if question[5]: %}
        <div>
        <a href="/question/download?img={{question[5]}}"><button class="btn btn-secondary float-right">첨부파일 : {{question[5]}}</button></a>
        </div>
        {% endif %}
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question[1] }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                 <div class="mb-2">{{ reporter[0] }}</div>
                 <div>{{ question[3] }}</div>
                </div>

            </div>
        </div>
    </div>
    {% if answer|length > 0 %}
    <h5 class="border-bottom my-3 py-2">{{ answer|length }}개의 답변이 있습니다.</h5>
    {% for answerset in answer %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answerset[0] }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answerset[2] }}</div>
                    <div>{{ answerset[1] }}</div>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    <form action="{{ url_for('answer.create', question_id= question[4]) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <div class="form-group">
            <textarea {% if not g.user %}disabled{% endif %}
                    name="content" placeholder="답변" id="content" class="form-control" rows="10"></textarea>
            <br>
            <input type="submit" value="답변등록" class="btn btn-secondary float-right">
        </div>
        <div><br></div>
    </form>
</div>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'pro.html' %}
{% block content %}
<div><br></div>
<div class="container table-responsive table-secondary shadow rounded-sm" style="margin-top :70px; margin-bottom:40px;">
    <h5 class="my-3 border-bottom pb-2 font-weight-bold">질문 등록</h5>
    <form method="post" class="post-form my-3" enctype = "multipart/form-data">
        {{ form.csrf_token }}
        <!-- ---------------------------------------- [edit] ---------------------------------------- -->
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <!-- ---------------------------------------------------------------------------------------- -->
        <div class="form-group">
            <!-- 
            <label for="subject">제목</label>
             -->
            <input type="text" placeholder="제목" class="form-control" name="subject" id="subject">
        </div>
        <div class="form-group">
            <!-- 
            <label for="content">내용</label>
             -->
            <input type="file" placeholder="파일첨부" class="btn btn-secondary float-right" name="file" id="file">
            <textarea placeholder="내용" class="form-control" name="content" id="content" rows="5" style="height: 500px;"></textarea>
            <br>
            <button type="submit" class="btn btn-secondary float-right">저장하기</button>
        </div>

        <div><br></div>
    </form>
</div>
<div><br></div>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'pro.html' %}
{% block content %}
<div class="container my-3"style="height:840px">
    <table class="table table-hover text-center">
        <thead>
        <tr class="text-center badge-secondary font-weight-bold text-wrap"> <!--thead-light-->
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>작성자</th>
            <th>작성일시</th>

            <th>비고</th>

            <!-- admin 로그인일때는 아래 코드를 넣어야 표가 보기 좋은데, 일반회원 기준은 없는게 맞네요 
            <th></th>
             -->
        </tr>
        </thead>
            <tbody>
            {% if question_list %}
                {% for question in question_list %}
                <tr class="text-center">
                    <td>{{ question[0]}}</td>
                    <td><a href="/question/detail?q={{question[0]}}">{{ question[1]}}</a></td>
                    <td>{{ question[3]}}</td>
                    <td>{{ question[4]}}</td>
                    {% if g.user == 'admin' %}
                    <td><a href="/question/delete?p_id={{ question[0] }}">삭제</a></td>
                    {% elif g.user == question[3] %}
                    <td><a href="/question/delete?p_id={{ question[0] }}&user={{question[3]}}">삭제</a></td>
                    {% endif %}
                </tr>
                {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>


    </table>
<!--    페이징    -->
    <ul class ="pagination justify-content-center">
        {% for page_num in range(1,lp) %}
            {% if page_num %}
                {% if page_num != p_page %}
                <li class="page-item">
                    <a class="page-link bg-light border-light text-dark rounded-0 shadow-none" href="?page={{page_num}}">{{page_num}}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link bg-secondary border-secondary text-white rounded-0 shadow-none" href="#">{{page_num}}</a>
                </li>
                {% endif %}
            {% else %}
                <li class="disabled">
                    <a class="page-link bg-secondary border-secondary text-white rounded-0 shadow-none" href="#">...</a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
    <br>
    <form method="post" class="post-form">
        {{ form.csrf_token }}
        <div class="form-group float-left" style="width:200px; height:30px;">
            <div class="input-group">
            <!-- 
            <label>제목검색</label>
             -->
            <input type="text" placeholder="제목 검색" class="form-control shadow-none border-secondary rounded-0" name="searchword" id="searchword"
                   value="{{ form.searchword.data or ''}}">
            <button type="submit" class="btn btn-secondary rounded-0">검색</button>
            </div>
        </div>
    </form>

    <a href="{{ url_for('question.create') }}" class="btn btn-secondary rounded-0" style="float:right;">질문 등록하기</a>
</div>
{% endblock %}